spring:
  jpa:
    show-sql: false
    database-platform: com.mindata.blockchain.core.sqlite.SQLiteDialect
    generate-ddl: true

rss:
  urls: http://f.cili001.com/index/rss?type=magnet&cid=25
aria2:
  url: http://jerrychel.qicp.vip:6800/jsonrpc
server:
  port: 8080
